# TODO: We shouldn't go with tokio_unstable to production

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
linker = "aarch64-linux-musl-gcc"

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
linker = "x86_64-linux-musl-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
codegen-units = 1
incremental = false

[build]
rustflags = [
    "--cfg", "tokio_unstable",
    "-C", "relocation-model=pic",
    "-C", "strip=debuginfo"
]
