name: Prebuild Dev Containers

permissions:
  packages: write

on:
  push:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/prebuild-devcontainers.yml'
      - rust-toolchain.toml
      - Dockerfile
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push devcontainer
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Platform devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ steps.prepare.outputs.repo-name }}/devcontainer
          imageTag: 0.1.0
          platform: linux/amd64,linux/arm64
          configFile: .devcontainer/devcontainer-build.json
          push: always
          cacheFrom: ghcr.io/${{ steps.prepare.outputs.repo-name }}/devcontainer
